//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boggle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Boggle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aa
        ///aah
        ///aahed
        ///aahing
        ///aahs
        ///aal
        ///aalii
        ///aaliis
        ///aals
        ///aardvark
        ///aardvarks
        ///aardwolf
        ///aardwolves
        ///aargh
        ///aarrgh
        ///aarrghh
        ///aarti
        ///aartis
        ///aas
        ///aasvogel
        ///aasvogels
        ///ab
        ///aba
        ///abac
        ///abaca
        ///abacas
        ///abaci
        ///aback
        ///abacs
        ///abacterial
        ///abactinal
        ///abactinally
        ///abactor
        ///abactors
        ///abacus
        ///abacuses
        ///abaft
        ///abaka
        ///abakas
        ///abalone
        ///abalones
        ///abamp
        ///abampere
        ///abamperes
        ///abamps
        ///aband
        ///abanded
        ///abanding
        ///abandon
        ///abandoned
        ///abandonedly
        ///abandonee
        ///abandonees
        ///abandoner
        ///abandoners
        ///abandoning
        ///abandonment
        ///abandonments
        ///abandons
        ///abandonware
        ///abandonwares
        ///abands
        ///abapical
        ///abas
        ///abase
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dictionary {
            get {
                return ResourceManager.GetString("dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream s1 {
            get {
                return ResourceManager.GetStream("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream s2 {
            get {
                return ResourceManager.GetStream("s2", resourceCulture);
            }
        }
    }
}
